### ISSUE TITLE
Use CSS to colorize textmate grammar

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#1]
Usually syntax coloration is customized with Eclipse preferences. My idea is to provide this customization with CSS too. To do that I need a SAC parser. By default Eclipse provides a SAC Parser implementation with batik that I will  use but we could use other SAC Parser.

@mickaelistria is it a problem to have this "optional" batic dependency?

My other idea is to customize grammar with TextMate theme. See https://github.com/angelozerr/textmate.java/issues/2

**Comment by mickaelistria** [comment]
I'm not sure this CSS customization is something we really need for the Eclipse IDE, as people are used to the Preferences. So I think it would be great if the whole CSS thing would be made fully optional and separate (ie just an alternative editor for preferences).

**Comment by angelozerr** [comment]
Thanks @mickaelistria for your answer.

> I'm not sure this CSS customization is something we really need for the Eclipse IDE, as people are used to the Preferences. 

VSCode does like this. Now I can get the VSCode stylesheet and have the same style inisde Eclipse.

Here my first result:

![textmate](https://cloud.githubusercontent.com/assets/1932211/20024121/dbd0f6a6-a2e4-11e6-8bf5-552ef964928b.png)

I must continue to clean API, code and fix bugs when user changes content of the editor.

> So I think it would be great if the whole CSS thing would be made fully optional and separate (ie just an alternative editor for preferences).

Yes sure, it's my idea too.
