### ISSUE TITLE
Change package to org.eclipse

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#11]

**Comment by angelozerr** [comment]
@mickaelistria I have changed package to org.eclipse.

Now we have **org.eclipse.language.textmate.core** and **org.eclipse.language.textmate.eclipse**. Is it OK?

**Comment by mickaelistria** [comment]
We'll see. As the project moves to Eclipse.org, it needs to get a name, and the name should be used in packages. There is no restriction for names except that it mustn't be a registered name. The name has to be decided when submitting the proposal and then Eclipse legal people check whether it's fine.
I didn't find that TextMate is a regstered trademark, however, I'm not sure "Eclipse Textmate" is the right name as it can drive people to imagine that TextMate editor is now part of Eclipe.org...
What about something like EclipseMate ?

**Comment by angelozerr** [comment]
I don't know. This project supports TextMate language grammar https://manual.macromates.com/en/language_grammars so I think we should keep TextMate name, no?

But if you are not OK, please give me a suggestion for projects names and  I will update it. Thanks!

**Comment by mickaelistria** [comment]
I will contact Eclipse legal right now to ask for advices and check whether having textmate in the package name is ok or not.

**Comment by angelozerr** [comment]
Thanks @mickaelistria !
