### ISSUE TITLE
Provide default theme

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#13]
Today, the CSS theme are hosted in the sample plugin https://github.com/angelozerr/textmate.java/tree/master/eclipse/org.eclipse.language.textmate.eclipse.samples/themes but I think it should be perhaps better to provide default theme, in other words I would like to move those CSS themes inside `org.eclipse.language.textmate.eclipse.`

@mickaelistria  are you OK with that?

**Comment by angelozerr** [comment]
@mickaelistria are you OK with that?

**Comment by mickaelistria** [comment]
Did you wrote those CSS themes or did you get them for somewhere else?
If you wrote them, then it's fine to move them; if not, it may introduce IP complexity when moving to Eclipse.org, so it'd be nice to keep them a bit separated at the moment. For example, as a fragment?

**Comment by angelozerr** [comment]
I have getted those themes from VSCode and adapt it , but those CSS was generated at runtime not written at hand.

**Comment by mickaelistria** [comment]
Ok, I think it's ok then. In this case, VSCode is the tool that allowed you to author those CSS, so you're the author.
Feel free to put move those files to UI plugin if you prefer it.

**Comment by angelozerr** [comment]
Thanks @mickaelistria I will move it to org.eclipse.language.textmate.eclipse
