### ISSUE TITLE
Add vscode-textmate tests

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#18]
@mickaelistria I'm developping JUnit classes wich will execute tests from the vscode-textmate at https://github.com/Microsoft/vscode-textmate/tree/master/test-cases 

Thoses files are JSON and grammar. I think it will be a problem when textmate.java will move to Eclipse.org, no?

For the moment I will add thoses tests inside org.eclipse.textmate4e.core and we will see after.

**Comment by mickaelistria** [comment]
Yes, it will make things a bit more complicated, but as long as those are separated bundles, it shouldn't be too hard to troubleshoot.

**Comment by angelozerr** [comment]
> it shouldn't be too hard to troubleshoot.

I have created a new project https://github.com/angelozerr/textmate.java/tree/master/org.eclipse.textmate4e.core.tests which contains vscode-textmate tests https://github.com/angelozerr/textmate.java/tree/master/org.eclipse.textmate4e.core.tests/src/test/resources/test-cases

Now I must execute thoses tests with JUnit and fix several problems with textmate.java to have the same features than vscode-textmate (I hope). Even if thoses tests will not be hosted inside Eclipse.org, they will give the capability to be improve textmate.java.

**Comment by angelozerr** [comment]
@mickaelistria I close this issue even if all tests are not passing:

![vscodetests](https://cloud.githubusercontent.com/assets/1932211/20959653/66bc34a2-bc5c-11e6-849c-4a7c1bfabd46.png)

For the moment, I have removed (see https://github.com/angelozerr/textmate.java/commit/41975678f84fa38ca0d49c97ac3eb760e8ef62f8#diff-cd8937f514714f96b43d2ad7ec06b413R25) from the test suite the tests which cause problem: there are 110 tests, 1 error and 3 failures. It seems problem (not sure that it's for all problem) comes from line which are encoded with no UTF-8.

So I think we have almost the same feature than VSCode. For performance topic, textmate.java is little slower than VSCode, but you don't see that with little file. With a very big file like https://raw.githubusercontent.com/Microsoft/TypeScript/master/lib/tsserver.js textmate.java takes 40s and VSCode takes 30s.
