### ISSUE TITLE
Support Grammar Injection

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#20]
Support Grammar Injection to support syntax coloration like:

 * HTML & JS
 * HTML & Freemarker

**Comment by angelozerr** [comment]
@mickaelistria for your information, grammar injection is now implemented. For instance here the result with PHP:

![phpeditor](https://cloud.githubusercontent.com/assets/1932211/20764643/5fd08a3a-b72f-11e6-86de-46f13868358e.png)

There are syntax coloration for PHP (I have added in the sample project a PHP editor) :

 * php
 * html: php textmate grammar declare a reference to the html grammar (grammar injection).
 * js : php textmate grammar declare a reference to the js grammar (grammar injection).

**Comment by angelozerr** [comment]
@kaloyan-raev please test the PHPEditor which works with TextMate. There are several problem with sync with editor and TextMate model but it starts working:

![phpeditor](https://cloud.githubusercontent.com/assets/1932211/20764643/5fd08a3a-b72f-11e6-86de-46f13868358e.png)

**Comment by mickaelistria** [comment]
Great improvement!
