### ISSUE TITLE
Select default TM theme according the Apparence Theme

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#22]
Today the TM default theme is everytime ligtht. When user changes the "Apparence Theme" to dark it should select the TM theme "dark".

**Comment by angelozerr** [comment]
@mickaelistria now we have 2 default themes "light" and "dark" which is choosen according the E4 Theme Appearance:

![tmtheme](https://cloud.githubusercontent.com/assets/1932211/21029688/36bcdf78-bd9b-11e6-969e-6426ba4cb141.gif)

To do that, the theme extension point was improved with new attribute **defaultForE4ThemeId**:

```
<extension
         point="org.eclipse.textmate4e.ui.themes">
      <theme
            id="org.eclipse.textmate4e.ui.themes.SolarizedLight"
      		name="%Theme.SolarizedLight.name"
            path="./themes/Solarized-light.css"
            defaultForE4ThemeId="*" >
      </theme>
      <theme
            id="org.eclipse.textmate4e.ui.themes.Dark"
      		name="%Theme.Dark.name"
            path="./themes/Dark.css"
            defaultForE4ThemeId="org.eclipse.e4.ui.css.theme.e4_dark" >            
      </theme>         
   </extension>

```

The defaultForE4ThemeId is the default TM theme to apply when E4 Theme (Classic, Dark, etc) is selected. @mickaelistria what do you think about the name defaultForE4ThemeId, do you like it?

**Comment by angelozerr** [comment]
@mickaelistria what do you think about the name defaultForE4ThemeId, do you like it?

**Comment by mickaelistria** [comment]
yes, I think it makes sense. However, I'd like to try a few more proposals:
* `workbenchTheme`
* `eclipseTheme`
* `applicationTheme`
* `targetWorkbenchTheme"

**Comment by angelozerr** [comment]
I like `eclipseThemeId ` what do you think @mickaelistria ?

**Comment by mickaelistria** [comment]
+1
