### ISSUE TITLE
Getting "Unknown extension point: 'org.eclipse.textmate4e.core.grammars' in plugin.xml

### ISSUE THREAD

**Issue by ainsley** [angelozerr/textmate.java#23]
I'm using the version from the update site, and it can't seem to find extension point 'org.eclipse.textmate4e.core.grammars' even though I have imported the correct bundles.

```
Require-Bundle: org.eclipse.ui,
 org.eclipse.core.runtime,
 org.eclipse.core.resources,
 org.eclipse.jdt.launching,
 org.eclipse.jdt.core,
 org.eclipse.debug.ui,
 org.eclipse.jdt.debug,
 org.eclipse.jdt.debug.ui,
 org.eclipse.jdt.ui,
 org.eclipse.jface.text,
 org.eclipse.ui,
 org.eclipse.core.resources,
 org.eclipse.core.filesystem,
 org.eclipse.ui.editors,
 org.eclipse.ui.views,
 org.eclipse.textmate4e.core,
 org.eclipse.textmate4e.ui
```

If I go to the "Add Extensions GUI in Eclipse, the extension point is missing there too:

![26319](https://cloud.githubusercontent.com/assets/201870/21038706/c0c5543c-bdcf-11e6-8bee-487f76819ebc.png)

**Comment by angelozerr** [comment]
Problem should be fixed but we have a problem with cloudbees https://opensagres.ci.cloudbees.com/job/textmate.java/ that we must fix it to recreate a new update site.

**Comment by angelozerr** [comment]
@ainsley please note that extension point API could change according developpers feedback like you. Any feedback are welcome!

My goal is to contribute to Eclipse https://projects.eclipse.org/proposals/textmate-support-eclipse-ide-textmate4e

**Comment by ainsley** [comment]
Is this resolved now in the update site?

**Comment by angelozerr** [comment]
yes, but now the extension point name has changed to `org.eclipse.tm4e.ui.themes.`

**Comment by ainsley** [comment]
Is there a guide where I can see instructions on how to integrate this into an existing plugin? Also, how are themes handled? Is Monokai in there?

**Comment by angelozerr** [comment]
I must improve wiki but you can read https://github.com/angelozerr/textmate.java/wiki/UI and see samples at https://github.com/angelozerr/textmate.java/tree/master/org.eclipse.tm4e.samples

I suggest you that you follow the Freemarker editor sample:

 * https://github.com/angelozerr/textmate.java/tree/master/org.eclipse.tm4e.samples/src/main/java/org/eclipse/tm4e/samples/freemarker

* https://github.com/angelozerr/textmate.java/blob/master/org.eclipse.tm4e.samples/plugin.xml#L142

For the themes today by default it supports light and dark theme, but you can regsiter your own theme with extension point (only CSS themes is supported for the moment, see https://github.com/angelozerr/textmate.java/issues/2). 

>  Is Monokai in there?

No but I can do it, please create a new issue.
