### ISSUE TITLE
Support for VSCode TextMate json parser.

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#3]
VSCode uses a JSON representation for TextMate like for C#. See https://github.com/OmniSharp/omnisharp-vscode/blob/master/syntaxes/csharp.json

Support this JSON Parser like XML PList.

**Comment by angelozerr** [comment]
@mickaelistria  here the result for C#

![c textmate](https://cloud.githubusercontent.com/assets/1932211/20056761/25d3caee-a4e8-11e6-9db3-b8ddf93a8332.png)

**Comment by mickaelistria** [comment]
Looks good. Did you already try to hook it to the generic editor extension for presentationReconciliers?

**Comment by angelozerr** [comment]
> Looks good. Did you already try to hook it to the generic editor extension for presentationReconciliers?

No, but I have created an issue for that https://github.com/angelozerr/textmate.java/issues/4

Before doing this issue I must clean my uggly code and fix https://github.com/angelozerr/textmate.java/issues/5

**Comment by mickaelistria** [comment]
Thanks, I tried the latest state from master and I think you can mark this issue as fixed.
