### ISSUE TITLE
NPE thrown

### ISSUE THREAD

**Issue by martinlippert** [angelozerr/textmate.java#34]
I am trying to use this with the generic editor for YAML files, but it throws this exception:

```
java.lang.NullPointerException
	at org.eclipse.tm4e.core.model.Tokenizer.tokenize(Tokenizer.java:49)
	at org.eclipse.tm4e.core.model.AbstractTMModel._updateTokensUntilLine(AbstractTMModel.java:533)
	at org.eclipse.tm4e.core.model.AbstractTMModel.lambda$0(AbstractTMModel.java:494)
	at org.eclipse.tm4e.core.model.AbstractTMModel._withModelTokensChangedEventBuilder(AbstractTMModel.java:435)
	at org.eclipse.tm4e.core.model.AbstractTMModel._revalidateTokensNow(AbstractTMModel.java:448)
	at org.eclipse.tm4e.core.model.AbstractTMModel.access$3(AbstractTMModel.java:447)
	at org.eclipse.tm4e.core.model.AbstractTMModel$BackgroundThread.run(AbstractTMModel.java:200)

```
I am using this grammar file:
https://raw.githubusercontent.com/textmate/yaml.tmbundle/master/Syntaxes/YAML.tmLanguage

and configured the extension like this:

```
   <extension
         point="org.eclipse.tm4e.core.grammars">
      <grammar
      		scopeName="cf.manifest.yml"
            path="./syntaxes/YAML.tmLanguage" >
      </grammar>      
      <scopeNameContentTypeBinding
            contentTypeId="org.springframework.boot.ide.manifest.yml"
            scopeName="cf.manifest.yml">
      </scopeNameContentTypeBinding>
   </extension>

```

Any idea what is going wrong here?

**Comment by angelozerr** [comment]
This error comes from that tm4e cannot find your grammar. The reason is that scopeName declared in the extension point should be the same than scopeName of your grammar

```
<key>scopeName</key>
<string>source.yaml</string>

```
. In other words you should use `source.yaml` and not `cf.manifest.yml`.

Please try and it should work:

```xml
   <extension
         point="org.eclipse.tm4e.core.grammars">
      <grammar
      		scopeName="source.yaml"
            path="./syntaxes/YAML.tmLanguage" >
      </grammar>      
      <scopeNameContentTypeBinding
            contentTypeId="org.springframework.boot.ide.manifest.yml"
            scopeName="source.yamll">
      </scopeNameContentTypeBinding>
   </extension>

```

**Comment by martinlippert** [comment]
Ah, right, I see, that works indeed. Many thanks!!!

I get the nice coloring. But I wonder why some values are sometimes rendered black instead of the nice color.

When I put something in like:

```
applications:
- name: hello
```

"hello" is rendered nicely. When I change that to "hellotest", it is rendered in black. Do you know why that happens?

**Comment by angelozerr** [comment]
> Many thanks!!!

You are welcome!

> But I wonder why some values are sometimes rendered black instead of the nice color.

I think it's the same bug than https://github.com/angelozerr/textmate.java/issues/31 https://github.com/angelozerr/textmate.java/issues/5

I suppose you have some feature which invalidate the text presentation of StyledText like validation, occurrences, folding, etc which update StyledText which causes this problem. 

As it's not possible to have the editor of each people to test each problem, I have decided to provide a Test generator https://github.com/angelozerr/textmate.java/issues/33 which will register each command (when text changed, when textviewer is invalidated, etc) and will generate a JUnit Java class with the problem. So after you will able to open your editor, play with your editor and close your editor and it will generate you a JUnit Java class with your commands. It will be easy for me to fix problem with your generated Java test class. I will try to finish my work this night.

**Comment by angelozerr** [comment]
@martinlippert please retry with master. I have fixed a little bug. I don't know if it will fix your problem.

**Comment by martinlippert** [comment]
@angelozerr that seems to fix it, thanks!!!
