### ISSUE TITLE
Add sample with GenericEditor presentationReconcliers

### ISSUE THREAD

**Issue by angelozerr** [angelozerr/textmate.java#4]

**Comment by angelozerr** [comment]
@mickaelistria I have added textmate.java quickly with GenericEditor inside LSP and here the result:

 * with CSS:

![syntaxcolorcss](https://cloud.githubusercontent.com/assets/1932211/20147232/9afe2ce0-a6a7-11e6-808d-bfd214ff1e45.png)

 * with JSON:

![syntaxcolorjson](https://cloud.githubusercontent.com/assets/1932211/20147277/bedfe158-a6a7-11e6-9536-6ffce3ad9ec2.png)

**Comment by mickaelistria** [comment]
The support doesn't have to be eclipse-language-service, it's actually better to keep it in textmate.java at the moment. Both eclipse-language-server and textmate.java could be installed and working simultaneously on the same Generic Editor.

**Comment by mickaelistria** [comment]
@angelozerr Is it something you managed to add?

**Comment by angelozerr** [comment]
https://github.com/angelozerr/textmate.java/tree/master/eclipse/org.eclipse.languageserver.languages.textmate manage that, no?

**Comment by mickaelistria** [comment]
Yep, feel free to close this issue.
